language: java
dist: xenial
services:
  - xvfb
env:
    global:
        -MOZ_HEADLESS=1
addons:
  chrome: stable
script: 
    mvn clean test -Dsuite="testng.xml"
before_install:
  - chmod +x /home/travis/build/AbstractaChile/demoKaufmann/chromedriver
