language: java
dist: xenial
services:
  - xvfb
addons:
  chrome: stable
script: 
    mvn clean test -Dsuite="testng.xml"
before_install:
  - chmod +x /home/travis/build/AbstractaChile/demoKaufmann/chromedriver
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
